[package]
name = "test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
audit-domain.workspace = true
auth-context.workspace = true
provisioning-domain.workspace = true
tenancy-domain.workspace = true

[lints]
workspace = true
