[package]
name = "db-migrator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
cell-migrations.workspace = true
platform-migrations.workspace = true
postgres-runtime.workspace = true
runtime-config.workspace = true
secret-resolution.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
